name: Run Browser Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  chrome-headless-tests:
    name: Chrome Headless Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build base image
        run: docker build -t app .

      - name: Build test image
        run: docker build -f tests/Dockerfile.test -t app-test .

      - name: Run Chrome Headless tests
        run: docker run --rm app-test 
        
  firefox-headless-tests:
    name: Firefox Headless Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build base image
        run: docker build -t app .

      - name: Build test image
        run: docker build -f tests/Dockerfile.firefox.test -t app-firefox-test .

      - name: Run Firefox Headless tests
        run: docker run --rm app-firefox-test
